sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: tyl200701

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGD8vXbz83yLrw3ZAH7
    access-key-secret: xdBYakBtxIpBsz7MTguTIEmtcFU26r
    bucket-name: web-framework0721

  servlet:
    max-file-size: 30MB
    max-request-size: 30MB

  redis:
    host: 10.211.55.10
    password: yzh1346as
    database: 0
    port: 6379